FROM mcr.microsoft.com/devcontainers/ruby:dev-3.3-bullseye

ENV RAILS_DEVELOPMENT_HOSTS=".githubpreview.dev,.app.github.dev"
ENV DATABASE_URL=postgresql://postgres:postgres@postgres:5432/azure_rails_starter_development

